---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUcpscX3A4pXwAWv1WOfIRB8DugYowDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTIwMjI0NTAwWhcNMjQxMTE4MjI0NTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AKVwywYYPU+Eq2SEpd/cg1k0kd9QOr5xb8SRouCvUqrJaLS9vypMm+LF5cWW7x04
    4HuBogXH7i9a80tI5j86uouN6YpVvocm/giFGnYBwlOtHA4+pHsxOPA7VPma4UTi
    0+Z7NJPsxSN8ZuXNpAxB5YAE87ea1HPs5WtRRjYnJsDP16lIA8nEw0fH+3G3EqV3
    qzpSdHAqR2//4cGbM+5ko9S8qDPsRHIo79iYtAKvBDM4KfVA0O3RJpwA82Hp4C24
    w5MELPStIicg3OgykHfmPu8Kcy/R3N4MXqtS4thhW5XM9MFv4YRaS78xUkfUDpLL
    5jn3kLoBj+NfZEM8vHe6wBOdkRskAE52g3mZxe2sx9r0hAb+a2dre51qAMMwLYK7
    A7bTEjpwyJXOtfFSWZHUCtw2bM9iYxvRUnbhUmMHDc/00MKOs6qBx9mTv4jP6MwQ
    in/vA4cU3aCMoO7nIosrqE/PvkFuBISkbLlGHiPyzRON7vveKXQc9Nw4GsAUjAvl
    /FnZ0eY0mcT8Lc6m5tX3z7z2Bg0ikVKnc6DWBdOC6yrha0HYVnIIF801KK56IMOn
    W6xoQ8JrUlxJqdjBG4pWUQt1MfVHzYXf+bzK5UFl/2xM7Jb27QSduxAG/Xqp1/b6
    Di9BgR9zqkyuE+c2/m2VHECyxyQL3pSpQE976Vu3DuY5AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTyP8mlYyfDGisU
    m2Ro5F/Ir7mLeDANBgkqhkiG9w0BAQ0FAAOCAgEASJtuYGo6xKP7LCvSlkBA93uO
    P3lSOQvl6wpyODtCCEUZm4F3ioAKVZjujiAmuYvydjSU8yfSR+Zr6E/LREkZA6hX
    2FQ/YFHkqnu21qnOJLRSj+hi3pdKQP767XGlfvecsF8Pel6Bx5vQJU5rlBEzsPoo
    fsbFwMR+x8Bic2j1uoXfQGK1ZNM3z1dJmiu9CdN7CV6IOS/o4lzfG23Rxqgi9BQy
    c8pAwNLcWHNCRodSWDWRI+jveY7iKAMl/ev4CyYeZTuuBpRLNlwSV8yr9LfEcKMM
    X/vnqGqHboI7WZpf1dzwSIp5WOFxn1VOH3k9WpH8HxjfJDY4mzDNLdLS3vNF8xzU
    ZqIYACetiF4MncgPGNDkVVMVS4n9KBuljv/qrCNYts8vpigcPuchNr8eaD/a/j0k
    xSQxtaOhxW8BNJ4ypmN5cn+t5GymRCNjRF2xQ3ZpwjOQuzUOQsQOUYrtEiZKn2Jv
    38RnjLaKgKu0h5tFhlrRChkMY0zhAZByHdBSDZC+hec68hyeTgN6gI+tc0WvGItG
    j9gRA0ghWKYLZo0hSl88m39iqNqrFxQxz28aiSeLbkBn15Qiftq/l1pXxw5gDE9d
    x1eHzEbDOhZxT9uNQDnv4rh6HC0HCCulrd2R2NcbTpIeijqsSh8WYqTOTghkTlEw
    SMd69uGhRCz9Jbfm5gQ=
    -----END CERTIFICATE-----
    
